// Genera los catálogos del menú Mods (framework) en los idiomas del mod, en el orden de en/es.json.
// Uso: node traducciones.js   (escribe verto13.gk2.craftingqueue/<idioma>.json)
// Cada idioma: [descripción del mod, secciones ×3, luego nombre y descripción de cada opción en el orden de KEYS].
const fs = require("fs"), path = require("path");
const dir = path.join(__dirname, "verto13.gk2.craftingqueue");
const P = "settings.Panel en pantalla.";
const KEYS = [
  "settings.Controles.Modificador", "settings.Vista rápida.Tecla", P + "Tecla", P + "TeclaEstiloReceta", P + "Visible",
  P + "Vista", P + "Recetas", P + "Contar", P + "Burbujas", P + "PinNuevas", P + "ColaVacia", P + "ConVentanas",
  P + "SiTapa", P + "Barra", P + "BarraSale", P + "Mover", P + "Lado", P + "Ancho", P + "AltoMaximo", P + "TamanoLetra",
  P + "OpacidadPanel", P + "OpacidadFondo", P + "TamanoIconos", P + "Escala", P + "VaciarCola",
];

const T = {
  de: [
    "Eine Handwerks-Liste auf dem Bildschirm: was du brauchst, was du hast und in welcher Truhe es liegt.",
    "Steuerung", "Rezeptvorschau", "Warteschlangen-Panel",
    "Zur Warteschlange hinzufügen", "Halte diese Taste und klicke mit rechts auf einen Gegenstand, ein Rezept, ein Gebäude oder ein Stadtprojekt, um es zur Warteschlange hinzuzufügen.",
    "Rezeptvorschau", "Halte diese Taste über einen beliebigen Gegenstand, um sein Rezept zu sehen.",
    "Panel ein-/ausblenden", "Blendet das Warteschlangen-Panel ein oder aus.",
    "Ausführliche / kompakte Rezepte", "Wechselt zwischen ausführlichem und kompaktem Rezeptstil.",
    "Panel anzeigen", "Zeigt die Warteschlange auf dem Bildschirm.",
    "Ansicht", "Pro Aufgabe: jede Aufgabe mit ihrem Rezept. Gesamt: alles, was die Warteschlange braucht, in einer Liste. Die Liste in der Knopfleiste des Panels macht dasselbe.",
    "Rezepte", "Ausführlich: eine Zutat pro Zeile, mit Namen. Kompakt: eine Zeile mit Symbolen. F4 macht dasselbe beim Spielen.",
    "Was als „vorhanden“ zählt", "Was du trägst und die Truhen der Zone, in der du bist (wie das Spiel beim Herstellen), nur was du trägst, oder nur die Truhen. Die Tasche und die Truhe im Panel machen dasselbe.",
    "Truhen-Blasen", "Blasen über den Truhen deiner Zone: für die ganze Warteschlange oder nur für Aufgaben mit aktivem Pin. Der Pin in der Knopfleiste macht dasselbe.",
    "Neue Aufgaben", "Neue Aufgaben starten mit aktivem Pin (ihre Materialien werden sofort an den Truhen markiert) oder ohne.",
    "Bei leerer Warteschlange", "Das Panel zeigt, wie man Dinge hinzufügt, oder bleibt verborgen, bis du etwas hinzufügst.",
    "Bei offenen Fenstern sichtbar", "Mit Truhen und Werkbänken: bleibt bei Truhen, Werkbänken, Läden und der Charakterseite und verschwindet bei Menüs, Dialogen und der Karte. Mit keinem: verschwindet bei jedem Fenster. Mit allen: immer sichtbar.",
    "Wenn es das Fenster verdeckt", "Mit offener Truhe, Werkbank oder offenem Technologiebaum: das Panel weicht aus oder klappt zu einem kleinen Reiter ein, oder bleibt oben. Das Auge in der Knopfleiste macht dasselbe.",
    "Knopfleiste", "Die Knöpfe des Panels draußen oder in ihrer ⋮-Ecke verstaut. Ein Klick auf die ⋮-Ecke macht dasselbe.",
    "Knöpfe erscheinen", "Seitlich am Panel oder oben darüber (bei schmalem Panel in zwei oder drei Reihen). Ein Rechtsklick auf die ⋮-Ecke macht dasselbe.",
    "Panel", "Beweglich: zieh es am Titel oder an der ⋮-Ecke und ändere die Größe am Eckgriff. Fest: es bleibt an seinem Platz. Das Schloss in der Knopfleiste macht dasselbe.",
    "Bildschirmseite", "Auf welcher Bildschirmseite das Panel sitzt. Auch Ziehen ändert sie.",
    "Breite", "Breite des Panels; lange Namen brechen in eine zweite Zeile um.",
    "Maximale Höhe", "Eine längere Warteschlange scrollt.",
    "Schriftgröße", "16 = die Größe des Spiels. 8, 16, 24 und 32 sind perfekt scharf, Größen dazwischen etwas ungleichmäßig. Umschalt + Mausrad über dem Panel macht dasselbe.",
    "Deckkraft des Panels", "Das ganze Panel: Text, Symbole, Knöpfe und Hintergrund. 1 = deckend.",
    "Deckkraft des Hintergrunds", "Nur der Hintergrund hinter jedem Rezept: 0 = unsichtbar, 1 = deckend.",
    "Symbolgröße", "Mit offenem Schloss wird das Panel breiter, wenn die Symbole nicht mehr passen. Mit geschlossenem Schloss behält das Panel seine Größe und die Symbole bleiben in seiner Breite. Strg + Mausrad über dem Panel macht dasselbe.",
    "Abstands-Skalierung", "Macht Symbole und Abstände kleiner oder größer; der Text bleibt in der scharfen Größe des Spiels.",
    "Warteschlange leeren", "Entfernt alle Aufgaben aus der Warteschlange des geladenen Spielstands. Zum Bestätigen zweimal klicken.",
  ],
  fr: [
    "Une liste d'artisanat à l'écran : ce qu'il te faut, ce que tu as et dans quel coffre.",
    "Commandes", "Aperçu de recette", "Panneau de la file",
    "Ajouter à la file", "Maintiens cette touche et fais un clic droit sur un objet, une recette, un bâtiment ou un chantier de la ville pour l'ajouter à la file.",
    "Aperçu de recette", "Maintiens cette touche sur n'importe quel objet pour voir sa recette.",
    "Afficher / masquer le panneau", "Affiche ou masque le panneau de la file.",
    "Recettes détaillées / compactes", "Passe du style détaillé au style compact des recettes.",
    "Afficher le panneau", "Affiche la file à l'écran.",
    "Vue", "Par tâche : chaque tâche avec sa recette. Total : tout ce que demande la file dans une seule liste. La liste de la barre de boutons du panneau fait la même chose.",
    "Recettes", "Détaillées : un ingrédient par ligne, avec son nom. Compactes : une ligne avec des icônes. F4 fait la même chose en jeu.",
    "Ce qui compte comme « possédé »", "Ce que tu portes et les coffres de la zone où tu es (comme le jeu pour fabriquer), seulement ce que tu portes, ou seulement les coffres. Le sac et le coffre du panneau font la même chose.",
    "Bulles sur les coffres", "Bulles au-dessus des coffres de ta zone : pour toute la file, ou seulement pour les tâches avec leur épingle activée. L'épingle de la barre de boutons fait la même chose.",
    "Nouvelles tâches", "Les nouvelles tâches commencent avec leur épingle activée (leurs matériaux sont marqués tout de suite sur les coffres) ou désactivée.",
    "Quand la file est vide", "Le panneau explique comment ajouter des choses, ou se cache jusqu'à ce que tu ajoutes quelque chose.",
    "Visible avec des fenêtres ouvertes", "Avec coffres et établis : reste avec les coffres, établis, boutiques et la page du personnage, et se cache avec les menus, dialogues et la carte. Aucune : se cache avec n'importe quelle fenêtre. Toutes : toujours visible.",
    "S'il couvre la fenêtre", "Avec un coffre, un établi ou l'arbre ouvert : le panneau se décale ou se replie en petit onglet, ou reste par-dessus. L'œil de la barre de boutons fait la même chose.",
    "Barre de boutons", "Les boutons du panneau sortis, ou rangés dans leur coin ⋮. Un clic sur le coin ⋮ fait la même chose.",
    "Les boutons sortent", "Sur le côté du panneau, ou au-dessus (sur deux ou trois lignes si le panneau est étroit). Un clic droit sur le coin ⋮ fait la même chose.",
    "Panneau", "Mobile : fais-le glisser par son titre ou son coin ⋮, et redimensionne-le par la poignée de son coin. Fixe : il reste en place. Le cadenas de la barre de boutons fait la même chose.",
    "Côté de l'écran", "De quel côté de l'écran se place le panneau. Le faire glisser le change aussi.",
    "Largeur", "Largeur du panneau ; les noms longs passent à la ligne.",
    "Hauteur maximale", "Une file plus longue défile.",
    "Taille du texte", "16 = la taille du jeu. 8, 16, 24 et 32 sont parfaitement nets, les tailles intermédiaires un peu irrégulières. Maj + molette sur le panneau fait la même chose.",
    "Opacité du panneau", "Tout le panneau : texte, icônes, boutons et fond. 1 = opaque.",
    "Opacité du fond", "Seulement le fond derrière chaque recette : 0 = invisible, 1 = opaque.",
    "Taille des icônes", "Avec le cadenas du panneau ouvert, le panneau s'élargit quand les icônes ne tiennent plus. Avec le cadenas fermé, le panneau garde sa taille et les icônes restent dans sa largeur. Ctrl + molette sur le panneau fait la même chose.",
    "Échelle des marges", "Réduit ou agrandit icônes et marges ; le texte reste à la taille nette du jeu.",
    "Vider la file", "Retire toutes les tâches de la file de la partie chargée. Clique deux fois pour confirmer.",
  ],
  "pt-br": [
    "Uma lista de criação na tela: o que você precisa, o que você tem e em qual baú está.",
    "Controles", "Prévia de receita", "Painel da fila",
    "Adicionar à fila", "Segure esta tecla e clique com o botão direito em um item, receita, construção ou obra da cidade para adicioná-lo à fila.",
    "Prévia de receita", "Segure esta tecla sobre qualquer item para ver a receita.",
    "Mostrar / ocultar painel", "Mostra ou oculta o painel da fila.",
    "Receitas detalhadas / compactas", "Alterna entre o estilo detalhado e o compacto das receitas.",
    "Mostrar painel", "Mostra a fila na tela.",
    "Visão", "Por tarefa: cada tarefa com sua receita. Total: tudo o que a fila pede em uma lista. A lista da barra de botões do painel faz o mesmo.",
    "Receitas", "Detalhadas: um ingrediente por linha, com o nome. Compactas: uma linha com ícones. F4 faz o mesmo enquanto você joga.",
    "O que conta como \"tenho\"", "O que você carrega e os baús da zona onde está (como o jogo ao criar), só o que você carrega, ou só os baús. A bolsa e o baú do painel fazem o mesmo.",
    "Balões nos baús", "Balões sobre os baús da sua zona: da fila inteira, ou só das tarefas com o alfinete ligado. O alfinete da barra de botões faz o mesmo.",
    "Tarefas novas", "As tarefas novas começam com o alfinete ligado (os materiais são marcados nos baús na hora) ou desligado.",
    "Com a fila vazia", "O painel mostra como adicionar coisas, ou se oculta até você adicionar algo.",
    "Visível com janelas abertas", "Com baús e bancadas: continua com baús, bancadas de criação, lojas e a página do personagem, e se oculta com menus, diálogos e o mapa. Nenhuma: se oculta com qualquer janela. Todas: sempre visível.",
    "Se cobrir a janela", "Com um baú, bancada ou a árvore aberta: o painel se afasta ou se recolhe em uma abinha, ou fica por cima. O olho da barra de botões faz o mesmo.",
    "Barra de botões", "Os botões do painel para fora, ou guardados no canto ⋮. Um clique no canto ⋮ faz o mesmo.",
    "Os botões saem", "Pela lateral do painel, ou por cima (em duas ou três linhas se for estreito). Um clique direito no canto ⋮ faz o mesmo.",
    "Painel", "Móvel: arraste pelo título ou pelo canto ⋮, e redimensione pela alça do canto. Fixo: fica no lugar. O cadeado da barra de botões faz o mesmo.",
    "Lado da tela", "Em que lado da tela fica o painel. Arrastá-lo também muda isso.",
    "Largura", "Largura do painel; nomes longos quebram para a linha seguinte.",
    "Altura máxima", "Uma fila mais longa rola.",
    "Tamanho do texto", "16 = o tamanho do jogo. 8, 16, 24 e 32 ficam perfeitamente nítidos; os intermediários, um pouco irregulares. Shift + roda do mouse sobre o painel faz o mesmo.",
    "Opacidade do painel", "Todo o painel: texto, ícones, botões e fundo. 1 = sólido.",
    "Opacidade do fundo", "Só o fundo atrás de cada receita: 0 = invisível, 1 = sólido.",
    "Tamanho dos ícones", "Com o cadeado do painel aberto, o painel se alarga quando os ícones não cabem mais. Com o cadeado fechado, o painel mantém o tamanho e os ícones ficam dentro da largura. Ctrl + roda do mouse sobre o painel faz o mesmo.",
    "Escala das margens", "Diminui ou aumenta ícones e margens; o texto fica no tamanho nítido do jogo.",
    "Esvaziar a fila", "Remove todas as tarefas da fila do jogo carregado. Clique duas vezes para confirmar.",
  ],
  ru: [
    "Список крафта на экране: что нужно, что есть и в каком сундуке лежит.",
    "Управление", "Быстрый рецепт", "Панель очереди",
    "Добавить в очередь", "Удерживайте эту клавишу и щёлкните правой кнопкой по предмету, рецепту, постройке или городскому проекту, чтобы добавить его в очередь.",
    "Быстрый рецепт", "Удерживайте эту клавишу над любым предметом, чтобы увидеть его рецепт.",
    "Показать / скрыть панель", "Показывает или скрывает панель очереди.",
    "Подробные / компактные рецепты", "Переключает подробный и компактный вид рецептов.",
    "Показывать панель", "Показывает очередь на экране.",
    "Вид", "По задачам: каждая задача со своим рецептом. Итого: всё, что нужно очереди, одним списком. Список на панели кнопок делает то же самое.",
    "Рецепты", "Подробные: один ингредиент в строке, с названием. Компактные: одна строка со значками. F4 делает то же самое во время игры.",
    "Что считается «есть»", "То, что при себе, и сундуки вашей зоны (как игра при крафте), только то, что при себе, или только сундуки. Сумка и сундук на панели делают то же самое.",
    "Пузыри над сундуками", "Пузыри над сундуками вашей зоны: для всей очереди или только для задач с включённой булавкой. Булавка на панели кнопок делает то же самое.",
    "Новые задачи", "Новые задачи начинаются с включённой булавкой (их материалы сразу отмечаются на сундуках) или с выключенной.",
    "Когда очередь пуста", "Панель подсказывает, как добавлять, или скрывается, пока вы что-нибудь не добавите.",
    "Видна при открытых окнах", "С сундуками и верстаками: остаётся с сундуками, верстаками, магазинами и страницей персонажа, и скрывается в меню, диалогах и на карте. Ни с какими: скрывается при любом окне. Со всеми: видна всегда.",
    "Если закрывает окно", "Когда открыт сундук, верстак или дерево технологий: панель отодвигается или сворачивается в маленькую вкладку, или остаётся сверху. Глаз на панели кнопок делает то же самое.",
    "Панель кнопок", "Кнопки панели снаружи или спрятаны в угол ⋮. Щелчок по углу ⋮ делает то же самое.",
    "Кнопки выходят", "Сбоку от панели или сверху (в две-три строки на узкой панели). Щелчок правой кнопкой по углу ⋮ делает то же самое.",
    "Панель", "Подвижная: перетаскивайте за заголовок или угол ⋮, меняйте размер за уголок. Закреплённая: остаётся на месте. Замок на панели кнопок делает то же самое.",
    "Сторона экрана", "С какой стороны экрана находится панель. Перетаскивание тоже её меняет.",
    "Ширина", "Ширина панели; длинные названия переносятся на новую строку.",
    "Максимальная высота", "Более длинная очередь прокручивается.",
    "Размер текста", "16 = размер игры. 8, 16, 24 и 32 идеально чёткие, промежуточные немного неровные. Shift + колесо мыши над панелью делает то же самое.",
    "Прозрачность панели", "Вся панель: текст, значки, кнопки и фон. 1 = непрозрачная.",
    "Прозрачность фона", "Только фон под каждым рецептом: 0 = невидимый, 1 = непрозрачный.",
    "Размер значков", "С открытым замком панель расширяется, когда значки перестают помещаться. С закрытым замком панель сохраняет размер, а значки остаются в её ширине. Ctrl + колесо мыши над панелью делает то же самое.",
    "Масштаб отступов", "Уменьшает или увеличивает значки и отступы; текст остаётся в чётком размере игры.",
    "Очистить очередь", "Удаляет все задачи из очереди загруженной игры. Нажмите дважды для подтверждения.",
  ],
  "uk-ua": [
    "Список крафту на екрані: що потрібно, що є і в якій скрині лежить.",
    "Керування", "Швидкий рецепт", "Панель черги",
    "Додати до черги", "Утримуйте цю клавішу й клацніть правою кнопкою на предмет, рецепт, будівлю чи міський проєкт, щоб додати його до черги.",
    "Швидкий рецепт", "Утримуйте цю клавішу над будь-яким предметом, щоб побачити його рецепт.",
    "Показати / сховати панель", "Показує або ховає панель черги.",
    "Детальні / компактні рецепти", "Перемикає детальний і компактний вигляд рецептів.",
    "Показувати панель", "Показує чергу на екрані.",
    "Вигляд", "За завданнями: кожне завдання зі своїм рецептом. Разом: усе, що потрібно черзі, одним списком. Список на панелі кнопок робить те саме.",
    "Рецепти", "Детальні: один інгредієнт у рядку, з назвою. Компактні: один рядок зі значками. F4 робить те саме під час гри.",
    "Що вважається «є»", "Те, що при собі, і скрині вашої зони (як гра під час крафту), тільки те, що при собі, або тільки скрині. Сумка і скриня на панелі роблять те саме.",
    "Бульбашки над скринями", "Бульбашки над скринями вашої зони: для всієї черги або лише для завдань з увімкненою шпилькою. Шпилька на панелі кнопок робить те саме.",
    "Нові завдання", "Нові завдання починаються з увімкненою шпилькою (їхні матеріали одразу позначаються на скринях) або з вимкненою.",
    "Коли черга порожня", "Панель підказує, як додавати, або ховається, доки ви щось не додасте.",
    "Видима з відкритими вікнами", "Зі скринями та верстатами: лишається зі скринями, верстатами, крамницями та сторінкою персонажа, і ховається в меню, діалогах і на мапі. З жодними: ховається з будь-яким вікном. З усіма: видима завжди.",
    "Якщо закриває вікно", "Коли відкрита скриня, верстат або дерево технологій: панель відсувається або згортається в маленьку вкладку, або лишається зверху. Око на панелі кнопок робить те саме.",
    "Панель кнопок", "Кнопки панелі назовні або сховані в куток ⋮. Клацання по кутку ⋮ робить те саме.",
    "Кнопки виходять", "Збоку панелі або зверху (у два-три рядки на вузькій панелі). Клацання правою кнопкою по кутку ⋮ робить те саме.",
    "Панель", "Рухома: перетягуйте за заголовок або куток ⋮, змінюйте розмір за куточок. Закріплена: лишається на місці. Замок на панелі кнопок робить те саме.",
    "Бік екрана", "З якого боку екрана панель. Перетягування теж його змінює.",
    "Ширина", "Ширина панелі; довгі назви переносяться на новий рядок.",
    "Максимальна висота", "Довша черга прокручується.",
    "Розмір тексту", "16 = розмір гри. 8, 16, 24 і 32 ідеально чіткі, проміжні трохи нерівні. Shift + коліщатко миші над панеллю робить те саме.",
    "Прозорість панелі", "Уся панель: текст, значки, кнопки й фон. 1 = непрозора.",
    "Прозорість фону", "Лише фон за кожним рецептом: 0 = невидимий, 1 = непрозорий.",
    "Розмір значків", "З відкритим замком панель розширюється, коли значки вже не вміщуються. Із закритим замком панель зберігає розмір, а значки лишаються в її ширині. Ctrl + коліщатко миші над панеллю робить те саме.",
    "Масштаб відступів", "Зменшує або збільшує значки та відступи; текст лишається в чіткому розмірі гри.",
    "Очистити чергу", "Видаляє всі завдання з черги завантаженої гри. Клацніть двічі для підтвердження.",
  ],
  it: [
    "Una lista di creazione sullo schermo: cosa ti serve, cosa hai e in quale baule si trova.",
    "Comandi", "Anteprima ricetta", "Pannello della coda",
    "Aggiungi alla coda", "Tieni premuto questo tasto e fai clic destro su un oggetto, una ricetta, una costruzione o un'opera cittadina per aggiungerlo alla coda.",
    "Anteprima ricetta", "Tieni premuto questo tasto su qualsiasi oggetto per vederne la ricetta.",
    "Mostra / nascondi pannello", "Mostra o nasconde il pannello della coda.",
    "Ricette dettagliate / compatte", "Passa dallo stile dettagliato a quello compatto delle ricette.",
    "Mostra pannello", "Mostra la coda sullo schermo.",
    "Vista", "Per attività: ogni attività con la sua ricetta. Totale: tutto ciò che chiede la coda in un'unica lista. La lista nella barra dei pulsanti del pannello fa lo stesso.",
    "Ricette", "Dettagliate: un ingrediente per riga, con il nome. Compatte: una riga con icone. F4 fa lo stesso mentre giochi.",
    "Cosa conta come \"posseduto\"", "Ciò che porti e i bauli della zona in cui sei (come il gioco quando crei), solo ciò che porti, o solo i bauli. La borsa e il baule del pannello fanno lo stesso.",
    "Fumetti sui bauli", "Fumetti sopra i bauli della tua zona: per tutta la coda, o solo per le attività con la puntina attiva. La puntina nella barra dei pulsanti fa lo stesso.",
    "Nuove attività", "Le nuove attività iniziano con la puntina attiva (i loro materiali vengono subito segnati sui bauli) o disattivata.",
    "Con la coda vuota", "Il pannello spiega come aggiungere cose, o si nasconde finché non aggiungi qualcosa.",
    "Visibile con finestre aperte", "Con bauli e banchi: resta con bauli, banchi da lavoro, negozi e la pagina del personaggio, e si nasconde con menu, dialoghi e la mappa. Nessuna: si nasconde con qualsiasi finestra. Tutte: sempre visibile.",
    "Se copre la finestra", "Con un baule, un banco o l'albero aperto: il pannello si sposta o si ripiega in una piccola linguetta, oppure resta sopra. L'occhio nella barra dei pulsanti fa lo stesso.",
    "Barra dei pulsanti", "I pulsanti del pannello fuori, o riposti nel loro angolo ⋮. Un clic sull'angolo ⋮ fa lo stesso.",
    "I pulsanti escono", "Sul lato del pannello, o sopra (su due o tre righe se è stretto). Un clic destro sull'angolo ⋮ fa lo stesso.",
    "Pannello", "Mobile: trascinalo dal titolo o dall'angolo ⋮ e ridimensionalo dalla maniglia dell'angolo. Fisso: resta al suo posto. Il lucchetto nella barra dei pulsanti fa lo stesso.",
    "Lato dello schermo", "Su quale lato dello schermo sta il pannello. Anche trascinarlo lo cambia.",
    "Larghezza", "Larghezza del pannello; i nomi lunghi vanno a capo.",
    "Altezza massima", "Una coda più lunga scorre.",
    "Dimensione del testo", "16 = la dimensione del gioco. 8, 16, 24 e 32 sono perfettamente nitidi, le misure intermedie un po' irregolari. Maiusc + rotellina sul pannello fa lo stesso.",
    "Opacità del pannello", "Tutto il pannello: testo, icone, pulsanti e sfondo. 1 = pieno.",
    "Opacità dello sfondo", "Solo lo sfondo dietro ogni ricetta: 0 = invisibile, 1 = pieno.",
    "Dimensione delle icone", "Con il lucchetto aperto, il pannello si allarga quando le icone non ci stanno più. Con il lucchetto chiuso, il pannello mantiene la sua dimensione e le icone restano nella sua larghezza. Ctrl + rotellina sul pannello fa lo stesso.",
    "Scala dei margini", "Rimpicciolisce o ingrandisce icone e margini; il testo resta alla dimensione nitida del gioco.",
    "Svuota la coda", "Rimuove tutte le attività dalla coda della partita caricata. Clicca due volte per confermare.",
  ],
  pl: [
    "Lista wytwarzania na ekranie: czego potrzebujesz, co masz i w której skrzyni to leży.",
    "Sterowanie", "Podgląd przepisu", "Panel kolejki",
    "Dodaj do kolejki", "Przytrzymaj ten klawisz i kliknij prawym przyciskiem przedmiot, przepis, budynek lub projekt miejski, aby dodać go do kolejki.",
    "Podgląd przepisu", "Przytrzymaj ten klawisz nad dowolnym przedmiotem, aby zobaczyć jego przepis.",
    "Pokaż / ukryj panel", "Pokazuje lub ukrywa panel kolejki.",
    "Przepisy szczegółowe / zwarte", "Przełącza między szczegółowym a zwartym stylem przepisów.",
    "Pokaż panel", "Pokazuje kolejkę na ekranie.",
    "Widok", "Według zadań: każde zadanie z jego przepisem. Razem: wszystko, czego potrzebuje kolejka, na jednej liście. Lista na pasku przycisków panelu robi to samo.",
    "Przepisy", "Szczegółowe: jeden składnik w wierszu, z nazwą. Zwarte: jeden wiersz z ikonami. F4 robi to samo podczas gry.",
    "Co liczy się jako „masz”", "To, co niesiesz, i skrzynie strefy, w której jesteś (jak gra przy wytwarzaniu), tylko to, co niesiesz, albo tylko skrzynie. Torba i skrzynia na panelu robią to samo.",
    "Dymki nad skrzyniami", "Dymki nad skrzyniami twojej strefy: dla całej kolejki lub tylko dla zadań z włączoną pinezką. Pinezka na pasku przycisków robi to samo.",
    "Nowe zadania", "Nowe zadania zaczynają z włączoną pinezką (ich materiały od razu są zaznaczane na skrzyniach) lub wyłączoną.",
    "Gdy kolejka jest pusta", "Panel pokazuje, jak dodawać rzeczy, albo chowa się, dopóki czegoś nie dodasz.",
    "Widoczny przy otwartych oknach", "Ze skrzyniami i stołami: zostaje przy skrzyniach, stołach rzemieślniczych, sklepach i stronie postaci, a chowa się w menu, dialogach i na mapie. Żadne: chowa się przy każdym oknie. Wszystkie: zawsze widoczny.",
    "Gdy zasłania okno", "Przy otwartej skrzyni, stole lub drzewku: panel odsuwa się lub zwija w małą zakładkę, albo zostaje na wierzchu. Oko na pasku przycisków robi to samo.",
    "Pasek przycisków", "Przyciski panelu na zewnątrz lub schowane w rogu ⋮. Kliknięcie rogu ⋮ robi to samo.",
    "Przyciski wychodzą", "Z boku panelu lub nad nim (w dwóch–trzech rzędach przy wąskim panelu). Kliknięcie prawym przyciskiem rogu ⋮ robi to samo.",
    "Panel", "Ruchomy: przeciągnij za tytuł lub róg ⋮ i zmień rozmiar uchwytem w rogu. Stały: zostaje na miejscu. Kłódka na pasku przycisków robi to samo.",
    "Strona ekranu", "Po której stronie ekranu jest panel. Przeciągnięcie też ją zmienia.",
    "Szerokość", "Szerokość panelu; długie nazwy przechodzą do nowego wiersza.",
    "Maksymalna wysokość", "Dłuższa kolejka się przewija.",
    "Rozmiar tekstu", "16 = rozmiar gry. 8, 16, 24 i 32 są idealnie ostre, pośrednie nieco nierówne. Shift + kółko myszy nad panelem robi to samo.",
    "Krycie panelu", "Cały panel: tekst, ikony, przyciski i tło. 1 = pełne.",
    "Krycie tła", "Tylko tło za każdym przepisem: 0 = niewidoczne, 1 = pełne.",
    "Rozmiar ikon", "Z otwartą kłódką panel się poszerza, gdy ikony się nie mieszczą. Z zamkniętą kłódką panel zachowuje rozmiar, a ikony mieszczą się w jego szerokości. Ctrl + kółko myszy nad panelem robi to samo.",
    "Skala odstępów", "Zmniejsza lub powiększa ikony i odstępy; tekst zostaje w ostrym rozmiarze gry.",
    "Wyczyść kolejkę", "Usuwa wszystkie zadania z kolejki wczytanej gry. Kliknij dwa razy, aby potwierdzić.",
  ],
  tr: [
    "Ekranda bir üretim listesi: neye ihtiyacın var, neyin var ve hangi sandıkta.",
    "Kontroller", "Tarif önizleme", "Sıra paneli",
    "Sıraya ekle", "Bu tuşu basılı tut ve sıraya eklemek için bir eşyaya, tarife, yapıya veya kasaba işine sağ tıkla.",
    "Tarif önizleme", "Tarifini görmek için bu tuşu herhangi bir eşyanın üzerinde basılı tut.",
    "Paneli göster / gizle", "Sıra panelini gösterir veya gizler.",
    "Ayrıntılı / sıkışık tarifler", "Ayrıntılı ve sıkışık tarif görünümü arasında geçiş yapar.",
    "Paneli göster", "Sırayı ekranda gösterir.",
    "Görünüm", "Göreve göre: her görev kendi tarifiyle. Toplam: sıranın istediği her şey tek listede. Panelin düğme çubuğundaki liste de aynısını yapar.",
    "Tarifler", "Ayrıntılı: her satırda adıyla bir malzeme. Sıkışık: simgeli tek satır. Oynarken F4 de aynısını yapar.",
    "\"Var\" sayılan", "Üzerindekiler ve bulunduğun bölgenin sandıkları (oyunun üretirken yaptığı gibi), yalnızca üzerindekiler ya da yalnızca sandıklar. Paneldeki çanta ve sandık da aynısını yapar.",
    "Sandık baloncukları", "Bölgendeki sandıkların üstünde baloncuklar: tüm sıra için ya da yalnızca iğnesi açık görevler için. Düğme çubuğundaki iğne de aynısını yapar.",
    "Yeni görevler", "Yeni görevler iğnesi açık (malzemeleri hemen sandıklarda işaretlenir) ya da kapalı başlar.",
    "Sıra boşken", "Panel nasıl ekleneceğini gösterir ya da bir şey ekleyene kadar gizlenir.",
    "Pencereler açıkken görünür", "Sandık ve tezgâhlarla: sandıklar, üretim tezgâhları, dükkânlar ve karakter sayfasıyla kalır; menüler, diyaloglar ve haritada gizlenir. Hiçbiri: her pencerede gizlenir. Hepsi: her zaman görünür.",
    "Pencereyi kapatırsa", "Bir sandık, tezgâh ya da ağaç açıkken: panel kenara kayar veya küçük bir sekmeye katlanır ya da üstte kalır. Düğme çubuğundaki göz de aynısını yapar.",
    "Düğme çubuğu", "Panelin düğmeleri dışarıda ya da ⋮ köşesinde saklı. ⋮ köşesine tıklamak da aynısını yapar.",
    "Düğmeler çıkar", "Panelin yanından ya da üstünden (dar panelde iki üç sıra). ⋮ köşesine sağ tıklamak da aynısını yapar.",
    "Panel", "Hareketli: başlığından ya da ⋮ köşesinden sürükle, köşe tutamacıyla boyutlandır. Sabit: yerinde kalır. Düğme çubuğundaki kilit de aynısını yapar.",
    "Ekran tarafı", "Panelin ekranın hangi tarafında durduğu. Sürüklemek de değiştirir.",
    "Genişlik", "Panel genişliği; uzun adlar alt satıra geçer.",
    "Azami yükseklik", "Daha uzun bir sıra kaydırılır.",
    "Yazı boyutu", "16 = oyunun kendi boyutu. 8, 16, 24 ve 32 kusursuz net, aradaki boyutlar biraz düzensiz. Panelin üstünde Shift + fare tekerleği de aynısını yapar.",
    "Panel opaklığı", "Tüm panel: yazı, simgeler, düğmeler ve arka plan. 1 = tam dolu.",
    "Arka plan opaklığı", "Yalnızca her tarifin arkasındaki arka plan: 0 = görünmez, 1 = tam dolu.",
    "Simge boyutu", "Kilit açıkken simgeler sığmayınca panel genişler. Kilit kapalıyken panel boyutunu korur ve simgeler genişliğinin içinde kalır. Panelin üstünde Ctrl + fare tekerleği de aynısını yapar.",
    "Boşluk ölçeği", "Simgeleri ve boşlukları küçültür ya da büyütür; yazı oyunun net boyutunda kalır.",
    "Sırayı boşalt", "Yüklü oyunun sırasındaki tüm görevleri kaldırır. Onaylamak için iki kez tıkla.",
  ],
  ja: [
    "画面上のクラフトToDoリスト：必要な物、持っている物、どのチェストにあるか。",
    "操作", "レシピのプレビュー", "キューパネル",
    "キューに追加", "このキーを押しながらアイテム・レシピ・建物・町の工事を右クリックすると、キューに追加します。",
    "レシピのプレビュー", "このキーを押しながらアイテムにカーソルを合わせると、レシピを表示します。",
    "パネルの表示／非表示", "キューパネルを表示または非表示にします。",
    "詳細／コンパクトなレシピ", "レシピの詳細表示とコンパクト表示を切り替えます。",
    "パネルを表示", "キューを画面に表示します。",
    "表示", "タスクごと：各タスクとそのレシピ。合計：キューに必要なすべてを1つのリストで。パネルのボタンバーのリストでも同じ操作ができます。",
    "レシピ", "詳細：材料を1行に1つ、名前付きで。コンパクト：アイコンを1行で。プレイ中はF4でも同じです。",
    "「持っている」に数えるもの", "持ち物と今いるエリアのチェスト（ゲームのクラフトと同じ）、持ち物のみ、またはチェストのみ。パネルの袋とチェストでも同じ操作ができます。",
    "チェストの吹き出し", "エリア内のチェストの上に吹き出し：キュー全体、またはピンをオンにしたタスクのみ。ボタンバーのピンでも同じ操作ができます。",
    "新しいタスク", "新しいタスクをピンオン（材料がすぐチェストに表示されます）またはオフで開始します。",
    "キューが空のとき", "パネルに追加方法を表示するか、何か追加するまで隠します。",
    "ウィンドウを開いているときに表示", "チェストと作業台：チェスト・作業台・店・キャラクターページでは表示し、メニュー・会話・マップでは隠します。なし：どのウィンドウでも隠します。すべて：常に表示します。",
    "ウィンドウに重なる場合", "チェスト・作業台・技術ツリーを開いているとき：パネルが横にずれるか小さなタブに折りたたまれる、またはそのまま上に表示されます。ボタンバーの目でも同じ操作ができます。",
    "ボタンバー", "パネルのボタンを外に出すか、⋮の角にしまいます。⋮の角をクリックしても同じです。",
    "ボタンの出る位置", "パネルの横、または上（幅が狭いと2〜3段）。⋮の角を右クリックしても同じです。",
    "パネル", "移動可能：タイトルか⋮の角でドラッグし、角のつまみでサイズを変更。固定：その場に留まります。ボタンバーの錠でも同じ操作ができます。",
    "画面の端", "パネルを画面のどちら側に置くか。ドラッグしても変わります。",
    "幅", "パネルの幅。長い名前は折り返します。",
    "最大の高さ", "長いキューはスクロールします。",
    "文字サイズ", "16＝ゲーム本来のサイズ。8・16・24・32はくっきり、その間のサイズは少しにじみます。パネル上でShift＋マウスホイールでも同じです。",
    "パネルの不透明度", "パネル全体：文字・アイコン・ボタン・背景。1＝不透明。",
    "背景の不透明度", "各レシピの背景のみ：0＝透明、1＝不透明。",
    "アイコンサイズ", "錠が開いていると、アイコンが収まらないときにパネルが広がります。錠が閉じていると、パネルはサイズを保ち、アイコンは幅に収まります。パネル上でCtrl＋マウスホイールでも同じです。",
    "余白の倍率", "アイコンと余白を小さく／大きくします。文字はゲームのくっきりしたサイズのままです。",
    "キューを空にする", "ロード中のセーブのキューからタスクをすべて削除します。2回クリックで確定します。",
  ],
  zh_cn: [
    "屏幕上的制作清单：需要什么、已有什么、在哪个箱子里。",
    "操作", "配方预览", "队列面板",
    "加入队列", "按住此键并右键点击物品、配方、建筑或城镇工程，即可加入队列。",
    "配方预览", "按住此键并将鼠标停在任意物品上，即可查看其配方。",
    "显示／隐藏面板", "显示或隐藏队列面板。",
    "详细／紧凑配方", "在详细和紧凑两种配方样式之间切换。",
    "显示面板", "在屏幕上显示队列。",
    "视图", "按任务：每个任务及其配方。合计：队列所需的一切汇总成一个列表。面板按钮栏中的列表也可切换。",
    "配方", "详细：每行一种材料，带名称。紧凑：一行图标。游戏中按 F4 也可切换。",
    "什么算作“已有”", "随身物品和所在区域的箱子（与游戏制作时相同）、仅随身物品，或仅箱子。面板上的背包和箱子也可切换。",
    "箱子气泡", "在所在区域的箱子上方显示气泡：整个队列，或仅限开启图钉的任务。按钮栏中的图钉也可切换。",
    "新任务", "新任务默认开启图钉（材料会立即在箱子上标出）或关闭。",
    "队列为空时", "面板显示如何添加，或在你添加内容前一直隐藏。",
    "打开窗口时显示", "箱子和工作台：在箱子、工作台、商店和角色页面时保持显示，在菜单、对话和地图中隐藏。无：打开任何窗口都隐藏。全部：始终显示。",
    "遮挡窗口时", "打开箱子、工作台或科技树时：面板移到一旁或折叠成小标签，或保持在上方。按钮栏中的眼睛也可切换。",
    "按钮栏", "面板的按钮显示在外面，或收进 ⋮ 角落。点击 ⋮ 角落也可切换。",
    "按钮出现位置", "在面板侧边，或在上方（面板较窄时分两三行）。右键点击 ⋮ 角落也可切换。",
    "面板", "可移动：拖动标题或 ⋮ 角落移动，拖动角落手柄调整大小。固定：保持原位。按钮栏中的锁也可切换。",
    "屏幕一侧", "面板位于屏幕哪一侧。拖动面板也会改变。",
    "宽度", "面板宽度；较长的名称会换行。",
    "最大高度", "队列较长时可滚动。",
    "文字大小", "16 = 游戏本身的大小。8、16、24、32 最清晰，中间的大小会略有不均。在面板上按 Shift + 鼠标滚轮也可调整。",
    "面板不透明度", "整个面板：文字、图标、按钮和背景。1 = 不透明。",
    "背景不透明度", "仅每个配方后面的背景：0 = 透明，1 = 不透明。",
    "图标大小", "面板的锁打开时，图标放不下会自动加宽面板。锁关闭时，面板保持大小，图标限制在其宽度内。在面板上按 Ctrl + 鼠标滚轮也可调整。",
    "边距缩放", "缩小或放大图标和边距；文字保持游戏的清晰大小。",
    "清空队列", "移除当前存档队列中的所有任务。点击两次确认。",
  ],
  zh_cht: [
    "螢幕上的製作清單：需要什麼、已有什麼、在哪個箱子裡。",
    "操作", "配方預覽", "佇列面板",
    "加入佇列", "按住此鍵並右鍵點擊物品、配方、建築或城鎮工程，即可加入佇列。",
    "配方預覽", "按住此鍵並將滑鼠停在任意物品上，即可查看其配方。",
    "顯示／隱藏面板", "顯示或隱藏佇列面板。",
    "詳細／緊湊配方", "在詳細和緊湊兩種配方樣式之間切換。",
    "顯示面板", "在螢幕上顯示佇列。",
    "檢視", "依任務：每個任務及其配方。合計：佇列所需的一切彙整成一個清單。面板按鈕列中的清單也可切換。",
    "配方", "詳細：每行一種材料，附名稱。緊湊：一行圖示。遊戲中按 F4 也可切換。",
    "什麼算作「已有」", "隨身物品和所在區域的箱子（與遊戲製作時相同）、僅隨身物品，或僅箱子。面板上的背包和箱子也可切換。",
    "箱子氣泡", "在所在區域的箱子上方顯示氣泡：整個佇列，或僅限開啟圖釘的任務。按鈕列中的圖釘也可切換。",
    "新任務", "新任務預設開啟圖釘（材料會立即在箱子上標出）或關閉。",
    "佇列為空時", "面板顯示如何加入，或在你加入內容前一直隱藏。",
    "開啟視窗時顯示", "箱子和工作台：在箱子、工作台、商店和角色頁面時保持顯示，在選單、對話和地圖中隱藏。無：開啟任何視窗都隱藏。全部：始終顯示。",
    "遮擋視窗時", "開啟箱子、工作台或科技樹時：面板移到一旁或摺疊成小標籤，或保持在上方。按鈕列中的眼睛也可切換。",
    "按鈕列", "面板的按鈕顯示在外面，或收進 ⋮ 角落。點擊 ⋮ 角落也可切換。",
    "按鈕出現位置", "在面板側邊，或在上方（面板較窄時分兩三行）。右鍵點擊 ⋮ 角落也可切換。",
    "面板", "可移動：拖曳標題或 ⋮ 角落移動，拖曳角落把手調整大小。固定：保持原位。按鈕列中的鎖也可切換。",
    "螢幕一側", "面板位於螢幕哪一側。拖曳面板也會改變。",
    "寬度", "面板寬度；較長的名稱會換行。",
    "最大高度", "佇列較長時可捲動。",
    "文字大小", "16 = 遊戲本身的大小。8、16、24、32 最清晰，中間的大小會略有不均。在面板上按 Shift + 滑鼠滾輪也可調整。",
    "面板不透明度", "整個面板：文字、圖示、按鈕和背景。1 = 不透明。",
    "背景不透明度", "僅每個配方後面的背景：0 = 透明，1 = 不透明。",
    "圖示大小", "面板的鎖打開時，圖示放不下會自動加寬面板。鎖關閉時，面板保持大小，圖示限制在其寬度內。在面板上按 Ctrl + 滑鼠滾輪也可調整。",
    "邊距縮放", "縮小或放大圖示和邊距；文字保持遊戲的清晰大小。",
    "清空佇列", "移除目前存檔佇列中的所有任務。點擊兩次確認。",
  ],
  ko: [
    "화면에 표시되는 제작 할 일 목록: 필요한 것, 가진 것, 어느 상자에 있는지.",
    "조작", "레시피 미리보기", "대기열 패널",
    "대기열에 추가", "이 키를 누른 채 아이템, 레시피, 건물 또는 마을 공사를 우클릭하면 대기열에 추가합니다.",
    "레시피 미리보기", "아무 아이템 위에서 이 키를 누르고 있으면 레시피를 보여 줍니다.",
    "패널 표시 / 숨기기", "대기열 패널을 표시하거나 숨깁니다.",
    "자세한 / 간단한 레시피", "레시피를 자세한 형태와 간단한 형태로 전환합니다.",
    "패널 표시", "대기열을 화면에 표시합니다.",
    "보기", "작업별: 각 작업과 그 레시피. 합계: 대기열에 필요한 모든 것을 하나의 목록으로. 패널 버튼 바의 목록도 같은 기능입니다.",
    "레시피", "자세히: 재료를 한 줄에 하나씩, 이름과 함께. 간단히: 아이콘 한 줄. 플레이 중 F4도 같은 기능입니다.",
    "\"가진 것\"으로 치는 것", "소지품과 현재 구역의 상자(게임의 제작과 같음), 소지품만, 또는 상자만. 패널의 가방과 상자도 같은 기능입니다.",
    "상자 말풍선", "구역 내 상자 위의 말풍선: 대기열 전체, 또는 핀이 켜진 작업만. 버튼 바의 핀도 같은 기능입니다.",
    "새 작업", "새 작업을 핀이 켜진 상태(재료가 바로 상자에 표시됨) 또는 꺼진 상태로 시작합니다.",
    "대기열이 비었을 때", "패널이 추가 방법을 보여 주거나, 무언가를 추가할 때까지 숨습니다.",
    "창이 열려 있을 때 표시", "상자와 작업대: 상자, 제작대, 상점, 캐릭터 페이지에서는 표시되고 메뉴, 대화, 지도에서는 숨습니다. 없음: 어떤 창이든 숨습니다. 모두: 항상 표시됩니다.",
    "창을 가릴 때", "상자, 작업대 또는 기술 트리가 열려 있을 때: 패널이 옆으로 비키거나 작은 탭으로 접히거나, 위에 그대로 있습니다. 버튼 바의 눈도 같은 기능입니다.",
    "버튼 바", "패널의 버튼을 밖에 두거나 ⋮ 모서리에 넣어 둡니다. ⋮ 모서리를 클릭해도 같습니다.",
    "버튼이 나오는 곳", "패널 옆, 또는 위쪽(패널이 좁으면 두세 줄). ⋮ 모서리를 우클릭해도 같습니다.",
    "패널", "이동 가능: 제목이나 ⋮ 모서리로 끌고, 모서리 손잡이로 크기를 바꿉니다. 고정: 제자리에 있습니다. 버튼 바의 자물쇠도 같은 기능입니다.",
    "화면 쪽", "패널이 화면의 어느 쪽에 붙는지. 끌어도 바뀝니다.",
    "너비", "패널 너비. 긴 이름은 줄이 바뀝니다.",
    "최대 높이", "더 긴 대기열은 스크롤됩니다.",
    "글자 크기", "16 = 게임 본래 크기. 8, 16, 24, 32는 완벽하게 선명하고 그 사이 크기는 약간 고르지 않습니다. 패널 위에서 Shift + 마우스 휠도 같습니다.",
    "패널 불투명도", "패널 전체: 글자, 아이콘, 버튼, 배경. 1 = 불투명.",
    "배경 불투명도", "각 레시피 뒤의 배경만: 0 = 투명, 1 = 불투명.",
    "아이콘 크기", "자물쇠가 열려 있으면 아이콘이 들어가지 않을 때 패널이 넓어집니다. 자물쇠가 닫혀 있으면 패널은 크기를 유지하고 아이콘은 너비 안에 머뭅니다. 패널 위에서 Ctrl + 마우스 휠도 같습니다.",
    "여백 배율", "아이콘과 여백을 작게 또는 크게 합니다. 글자는 게임의 선명한 크기를 유지합니다.",
    "대기열 비우기", "불러온 게임의 대기열에서 모든 작업을 제거합니다. 확인하려면 두 번 클릭하세요.",
  ],
  th: [
    "รายการสิ่งที่จะคราฟต์บนหน้าจอ: ต้องใช้อะไร มีอะไรแล้ว และอยู่ในหีบไหน",
    "การควบคุม", "ดูสูตรแบบด่วน", "แผงคิว",
    "เพิ่มลงคิว", "กดปุ่มนี้ค้างไว้แล้วคลิกขวาที่ไอเทม สูตร สิ่งก่อสร้าง หรืองานของเมือง เพื่อเพิ่มลงคิว",
    "ดูสูตรแบบด่วน", "กดปุ่มนี้ค้างไว้บนไอเทมใดก็ได้เพื่อดูสูตร",
    "แสดง / ซ่อนแผง", "แสดงหรือซ่อนแผงคิว",
    "สูตรแบบละเอียด / แบบย่อ", "สลับระหว่างสูตรแบบละเอียดและแบบย่อ",
    "แสดงแผง", "แสดงคิวบนหน้าจอ",
    "มุมมอง", "ตามงาน: แต่ละงานพร้อมสูตร รวม: ทุกอย่างที่คิวต้องการในรายการเดียว รายการในแถบปุ่มของแผงก็ทำแบบเดียวกัน",
    "สูตร", "ละเอียด: ส่วนผสมบรรทัดละหนึ่งอย่างพร้อมชื่อ แบบย่อ: หนึ่งบรรทัดเป็นไอคอน กด F4 ระหว่างเล่นก็ทำแบบเดียวกัน",
    "อะไรนับว่า \"มีแล้ว\"", "ของที่พกอยู่และหีบในโซนที่อยู่ (เหมือนตอนเกมคราฟต์) เฉพาะของที่พก หรือเฉพาะหีบ กระเป๋าและหีบบนแผงก็ทำแบบเดียวกัน",
    "ฟองบนหีบ", "ฟองเหนือหีบในโซนของคุณ: สำหรับทั้งคิว หรือเฉพาะงานที่เปิดหมุดไว้ หมุดในแถบปุ่มก็ทำแบบเดียวกัน",
    "งานใหม่", "งานใหม่เริ่มแบบเปิดหมุด (วัตถุดิบจะถูกทำเครื่องหมายบนหีบทันที) หรือปิดหมุด",
    "เมื่อคิวว่าง", "แผงแสดงวิธีเพิ่มของ หรือซ่อนไว้จนกว่าจะเพิ่มอะไรสักอย่าง",
    "แสดงขณะเปิดหน้าต่าง", "หีบและโต๊ะ: แสดงอยู่กับหีบ โต๊ะคราฟต์ ร้านค้า และหน้าตัวละคร และซ่อนเมื่อเปิดเมนู บทสนทนา และแผนที่ ไม่มี: ซ่อนเมื่อเปิดหน้าต่างใดก็ได้ ทั้งหมด: แสดงตลอด",
    "ถ้าบังหน้าต่าง", "เมื่อเปิดหีบ โต๊ะ หรือต้นไม้เทคโนโลยี: แผงจะเลื่อนหลบหรือพับเป็นแท็บเล็ก ๆ หรืออยู่ด้านบน ดวงตาในแถบปุ่มก็ทำแบบเดียวกัน",
    "แถบปุ่ม", "ปุ่มของแผงอยู่ด้านนอก หรือเก็บไว้ที่มุม ⋮ คลิกที่มุม ⋮ ก็ทำแบบเดียวกัน",
    "ปุ่มออกมาทาง", "ด้านข้างของแผง หรือด้านบน (สองสามแถวถ้าแผงแคบ) คลิกขวาที่มุม ⋮ ก็ทำแบบเดียวกัน",
    "แผง", "เคลื่อนย้ายได้: ลากที่ชื่อหรือมุม ⋮ และปรับขนาดที่มุม ตรึง: อยู่กับที่ แม่กุญแจในแถบปุ่มก็ทำแบบเดียวกัน",
    "ด้านของหน้าจอ", "แผงอยู่ด้านไหนของหน้าจอ การลากก็เปลี่ยนได้",
    "ความกว้าง", "ความกว้างของแผง ชื่อยาวจะขึ้นบรรทัดใหม่",
    "ความสูงสูงสุด", "คิวที่ยาวกว่าจะเลื่อนได้",
    "ขนาดตัวอักษร", "16 = ขนาดของเกม 8, 16, 24 และ 32 คมชัดที่สุด ขนาดระหว่างนั้นจะไม่สม่ำเสมอเล็กน้อย Shift + ล้อเมาส์บนแผงก็ทำแบบเดียวกัน",
    "ความทึบของแผง", "ทั้งแผง: ตัวอักษร ไอคอน ปุ่ม และพื้นหลัง 1 = ทึบ",
    "ความทึบของพื้นหลัง", "เฉพาะพื้นหลังหลังแต่ละสูตร: 0 = มองไม่เห็น 1 = ทึบ",
    "ขนาดไอคอน", "เมื่อแม่กุญแจเปิด แผงจะกว้างขึ้นเมื่อไอคอนไม่พอ เมื่อแม่กุญแจปิด แผงคงขนาดเดิมและไอคอนอยู่ในความกว้างนั้น Ctrl + ล้อเมาส์บนแผงก็ทำแบบเดียวกัน",
    "สเกลระยะขอบ", "ย่อหรือขยายไอคอนและระยะขอบ ตัวอักษรยังคงขนาดคมชัดของเกม",
    "ล้างคิว", "ลบงานทั้งหมดออกจากคิวของเกมที่โหลดอยู่ คลิกสองครั้งเพื่อยืนยัน",
  ],
  vn: [
    "Danh sách chế tạo trên màn hình: cần gì, đã có gì và nằm trong rương nào.",
    "Điều khiển", "Xem nhanh công thức", "Bảng hàng đợi",
    "Thêm vào hàng đợi", "Giữ phím này và nhấp chuột phải vào vật phẩm, công thức, công trình hoặc công trình thị trấn để thêm vào hàng đợi.",
    "Xem nhanh công thức", "Giữ phím này trên bất kỳ vật phẩm nào để xem công thức.",
    "Hiện / ẩn bảng", "Hiện hoặc ẩn bảng hàng đợi.",
    "Công thức chi tiết / gọn", "Chuyển giữa kiểu công thức chi tiết và gọn.",
    "Hiện bảng", "Hiện hàng đợi trên màn hình.",
    "Chế độ xem", "Theo nhiệm vụ: mỗi nhiệm vụ với công thức của nó. Tổng: mọi thứ hàng đợi cần trong một danh sách. Danh sách trên thanh nút của bảng cũng làm như vậy.",
    "Công thức", "Chi tiết: mỗi dòng một nguyên liệu, kèm tên. Gọn: một dòng biểu tượng. F4 khi chơi cũng làm như vậy.",
    "Thế nào là \"đã có\"", "Đồ mang theo và các rương trong khu vực bạn đang ở (như trò chơi khi chế tạo), chỉ đồ mang theo, hoặc chỉ các rương. Túi và rương trên bảng cũng làm như vậy.",
    "Bong bóng trên rương", "Bong bóng trên các rương trong khu vực: cho cả hàng đợi, hoặc chỉ các nhiệm vụ bật ghim. Ghim trên thanh nút cũng làm như vậy.",
    "Nhiệm vụ mới", "Nhiệm vụ mới bắt đầu với ghim bật (nguyên liệu được đánh dấu ngay trên rương) hoặc tắt.",
    "Khi hàng đợi trống", "Bảng hướng dẫn cách thêm, hoặc ẩn cho đến khi bạn thêm thứ gì đó.",
    "Hiện khi mở cửa sổ", "Với rương và bàn: vẫn hiện với rương, bàn chế tạo, cửa hàng và trang nhân vật, ẩn với menu, hội thoại và bản đồ. Không có: ẩn với mọi cửa sổ. Tất cả: luôn hiện.",
    "Nếu che cửa sổ", "Khi mở rương, bàn hoặc cây công nghệ: bảng dịch sang bên hoặc thu thành một thẻ nhỏ, hoặc nằm đè lên. Con mắt trên thanh nút cũng làm như vậy.",
    "Thanh nút", "Các nút của bảng ở ngoài, hoặc cất vào góc ⋮. Nhấp vào góc ⋮ cũng làm như vậy.",
    "Nút xuất hiện", "Ở cạnh bảng, hoặc phía trên (hai ba hàng nếu bảng hẹp). Nhấp chuột phải vào góc ⋮ cũng làm như vậy.",
    "Bảng", "Di chuyển được: kéo bằng tiêu đề hoặc góc ⋮, đổi kích thước bằng tay cầm ở góc. Cố định: ở yên chỗ cũ. Ổ khóa trên thanh nút cũng làm như vậy.",
    "Cạnh màn hình", "Bảng nằm ở cạnh nào của màn hình. Kéo bảng cũng thay đổi.",
    "Chiều rộng", "Chiều rộng của bảng; tên dài sẽ xuống dòng.",
    "Chiều cao tối đa", "Hàng đợi dài hơn sẽ cuộn.",
    "Cỡ chữ", "16 = cỡ của trò chơi. 8, 16, 24 và 32 sắc nét hoàn hảo, các cỡ ở giữa hơi không đều. Shift + con lăn chuột trên bảng cũng làm như vậy.",
    "Độ mờ của bảng", "Toàn bộ bảng: chữ, biểu tượng, nút và nền. 1 = đặc.",
    "Độ mờ của nền", "Chỉ nền phía sau mỗi công thức: 0 = vô hình, 1 = đặc.",
    "Cỡ biểu tượng", "Khi ổ khóa mở, bảng rộng ra khi biểu tượng không còn vừa. Khi ổ khóa đóng, bảng giữ kích thước và biểu tượng nằm trong chiều rộng đó. Ctrl + con lăn chuột trên bảng cũng làm như vậy.",
    "Tỉ lệ lề", "Thu nhỏ hoặc phóng to biểu tượng và lề; chữ giữ cỡ sắc nét của trò chơi.",
    "Xóa hàng đợi", "Xóa mọi nhiệm vụ khỏi hàng đợi của bản lưu đang tải. Nhấp hai lần để xác nhận.",
  ],
};

for (const [lang, t] of Object.entries(T)) {
  const expected = 4 + KEYS.length * 2;
  if (t.length !== expected) throw new Error(`${lang}: ${t.length} textos, se esperaban ${expected}`);
  const o = { "mod.name": "Crafting Queue", "mod.description": t[0],
    "sections.Controles": t[1], "sections.Vista rápida": t[2], "sections.Panel en pantalla": t[3] };
  KEYS.forEach((k, i) => { o[k + ".name"] = t[4 + i * 2]; o[k + ".description"] = t[5 + i * 2]; });
  fs.writeFileSync(path.join(dir, lang + ".json"), JSON.stringify(o, null, 2) + "\n");
  console.log(lang, Object.keys(o).length, "claves");
}
